---
- name: "Lab 3 - Installation et configuration de la stack Web Nginx"
  hosts: web    # on souhaite configurer Nginx UNIQUEMENT sur les "serveurs" web de l'inventaire, pas sur les bases de données
  become: true  # car chaque tâche du playbook nécessite les droits root
  gather_facts: true  # collecte des informations (IP, Hostname...)

  pre_tasks:
    # ---------------------------------------------------------------------------------------
    # ÉTAPE PRÉALABLE : Rafraîchir le gestionnaire de paquets (module apt spécifique à l'OS)
    # ---------------------------------------------------------------------------------------
    - name: "S'assurer que l'index des paquets est à jour"
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts["os_family"] == "Debian"  # le module "ansible.builtin.apt" doit uniquement être utilisé sur Debian (c'est yum/dnf sur RHEL par exemple)

  tasks:
    # ---------------------------------------------------------------------------------------
    # TÂCHE 04 : Installer les outils système (via le module générique)
    # ---------------------------------------------------------------------------------------
    - name: "Installer les outils de base"
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - git
        - htop

    # ---------------------------------------------------------------------------------------
    # TÂCHE 01 : Installer le serveur Web Nginx (via le module générique)
    # ---------------------------------------------------------------------------------------
    - name: "S'assurer que le package Nginx est installé"
      ansible.builtin.package:
        name: nginx
        state: present

    # ---------------------------------------------------------------------------------------
    # TÂCHE 02 & 03 : Déployer la page dynamique et lier le Handler
    # ---------------------------------------------------------------------------------------
    - name: "Générer la page d'accueil dynamique index.html"
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        owner: www-data  # Propriétaire requis pour que Nginx puisse lire le fichier
        group: www-data
        mode: '0644'
      notify: "Déclencher le redémarrage de Nginx"

  handlers:
    # ---------------------------------------------------------------------------------------
    # GESTIONNAIRE : Redémarrage à chaud
    # ---------------------------------------------------------------------------------------
    - name: "Déclencher le redémarrage de Nginx"
      ansible.builtin.service:
        name: nginx
        state: restarted